apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: logging
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        5
        Daemon       Off
        Log_Level    info
        Parsers_File /fluent-bit/etc/parsers.conf
        HTTP_Server  On
        HTTP_Port    2020

    # Input section to tail logs from all containers in the default namespace
    [INPUT]
        Name          tail
        Path          /var/log/containers/*.log
        Parser        docker
        Tag           kube.*
        DB            /fluent-bit/db/fluentbit.db
        Mem_Buf_Limit 5MB
        Skip_Long_Lines On

    # Filter to enrich logs with Kubernetes metadata
    [FILTER]
        Name          kubernetes
        Match         kube.*
        Kube_URL      https://kubernetes.default.svc:443
        Merge_Log     On
        K8S-Logging.Parser On
        K8S-Logging.Exclude On

    # Output to Elasticsearch
    [OUTPUT]
        Name          es
        Match         *
        Host          elasticsearch
        Port          9200
        Index         fluentbit-${date}
        Type          _doc
        Logstash_Format Off

  parsers.conf: |
    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On
        Types       container_name=string,container_id=string,log=string
