
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: guy-tomer-alb-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:us-east-1:992382545251:certificate/4c35c483-4d3c-413c-a95a-14c0aae5b5e2"
    external-dns.alpha.kubernetes.io/hostname: "status-page.org"
spec:
  ingressClassName: alb
  rules:
    - host: status-page.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx
                port:
                  number: 80