apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sql
  namespace: default
spec:
  replicas: {{ .Values.postgresql.replicas }}
  selector:
    matchLabels:
      app: sql
  template:
    metadata:
      labels:
        app: sql
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: sql
          image: "{{ .Values.postgresql.image.repository }}:{{ .Values.postgresql.image.tag }}"
          env:
            - name: POSTGRES_USER
              value: "{{ .Values.postgresql.username }}"
            - name: POSTGRES_PASSWORD
              value: "{{ .Values.postgresql.password }}"
            - name: POSTGRES_DB
              value: "{{ .Values.postgresql.database }}"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: pgdata
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: guy_tomer_storage_class
        resources:
          requests:
            storage: 1Gi
