apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClass.name | default "guy_tomer_storage_class" }}
provisioner: ebs.csi.aws.com
parameters:
  type: {{ .Values.storageClass.type | default "gp2" }}
  fsType: ext4
  encrypted: "true"
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
