apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sql
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sql
  template:
    metadata:
      labels:
        app: sql
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: sql
          image: 992382545251.dkr.ecr.us-east-1.amazonaws.com/tomer-guy-final-project/sql:latest
          env:
            - name: POSTGRES_USER
              value: "admin_statuspage"
            - name: POSTGRES_PASSWORD
              value: "0123456789"
            - name: POSTGRES_DB
              value: "db_statuspage"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: pgdata
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
