apiVersion: v1
kind: Service
metadata:
  name: sql
  namespace: default
spec:
  selector:
    app: sql
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      name: sql
# TODO - Change in docker-compose and configuation.py the sql host to postgresql
