apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        5
        Log_Level    info
        Parsers_File parsers.conf

    [INPUT]
        Name        tail
        Path        /var/log/containers/*.log
        Tag        kube.*

    [OUTPUT]
        Name  opensearch
        Match kube.*
        Host  opensearch.status-page.org 
        Port  443
        Index fluentbit
        Type  _doc
        AWS_Region us-east-1
        AWS_Auth On
