grafana:
  enabled: true
  service:
    type: ClusterIP
  ingress:
    enabled: false
  auth:
    login_url: /grafana-login
  # ini:
  #   server:
  #     domain: status-page.org
  #     root_url: "%(protocol)s://%(domain)s:%(http_port)s/grafana" 