# grafana:
#   enabled: true
#   service:
#     type: ClusterIP
#   ingress:
#     enabled: false
#   # grafana.ini:
#   #   server:
#   #     domain: status-page.org
#   #     root_url: "%(protocol)s://%(domain)s/grafana/"
#   #     serve_from_sub_path: true

#   # Persistence settings to retain data across restarts
#   persistence:
#     enabled: true
#     storageClassName: guy-tomer-storage-class
#     accessModes:
#       - ReadWriteOnce
#     size: 10Gi

#   # Admin credentials
#   adminUser: admin
#   adminPassword: admin123
# # grafana:
#   extraConfigmapMounts:
#     - name: monitoring-grafana
#       mountPath: /etc/grafana/grafana.ini
#       subPath: grafana.ini
#       configMap: monitoring-grafana
grafana:
  enabled: true
  service:
    type: ClusterIP
  ingress:
    enabled: false
  persistence:
    enabled: true
    storageClassName: guy-tomer-storage-class
    accessModes:
      - ReadWriteOnce
    size: 10Gi
  datasources:
    elasticsearch:
      url: "https://elasticsearch-master.default.svc.cluster.local:9200"  # Replace this with the ALB URL
      access: "proxy"
      basic_auth:
        enabled: true
        username: "elastic"  # Provide the necessary username
        password: "admin123"  # Provide the necessary password
      ssl:
        enabled: true
        skip_verify: true  # Set to true only for self-signed certs
      index: "eks-logs*"        # Your index pattern
      time_field_name: "@timestamp"  # The field name for time-based data

  # Admin credentials
  # adminUser: admin
  # adminPassword: admin123
  # grafana:
  extraConfigmapMounts:
    - name: monitoring-grafana
      mountPath: /etc/grafana/grafana.ini
      subPath: grafana.ini
      configMap: monitoring-grafana
  # Provision grafana-dashboards-kubernetes
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: "grafana-dashboards-kubernetes"
          orgId: 1
          folder: "Kubernetes"
          type: file
          disableDeletion: true
          editable: true
          options:
            path: /var/lib/grafana/dashboards/grafana-dashboards-kubernetes
  dashboards:
    grafana-dashboards-kubernetes:
      k8s-system-api-server:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-system-api-server.json
        token: ""
      k8s-system-coredns:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-system-coredns.json
        token: ""
      k8s-views-global:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-global.json
        token: ""
      k8s-views-namespaces:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-namespaces.json
        token: ""
      k8s-views-nodes:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-nodes.json
        token: ""
      k8s-views-pods:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-pods.json
        token: ""