grafana:
  enabled: true
  service:
    type: ClusterIP
  ingress:
    enabled: false
  grafana.ini:
    server:
      domain: status-page.org
      root_url: "%(protocol)s://%(domain)s/grafana/"
      serve_from_sub_path: true

  # Persistence settings to retain data across restarts
  persistence:
    enabled: true
    storageClassName: gp2
    accessModes:
      - ReadWriteOnce
    size: 10Gi

  # Admin credentials
  adminUser: admin
  adminPassword: admin123