# imagePullSecret: ecr-secret
nginx:
  replicas: 1
  image:
    repository: 992382545251.dkr.ecr.us-east-1.amazonaws.com/tomer-guy-final-project/nginx
    tag: latest
# postgresql:
#   replicas: 1
#   image:
#     repository: 992382545251.dkr.ecr.us-east-1.amazonaws.com/tomer-guy-final-project/sql
#     tag: latest
#   username: "admin_statuspage"
#   password: "0123456789"
#   database: "db_statuspage"



status_page:
  replicas: 1
  image:
    repository: 992382545251.dkr.ecr.us-east-1.amazonaws.com/tomer-guy-final-project/app
    tag: latest
  dbhost: "<RDS_ENDPOINT>"
  dbname: "db_statuspage"
  dbuser: "admin_statuspage"
  dbpassword: "0123456789"
  redishost: "redis"
  secret_key: "O32MGYzFbXL4EqKgVpwrDT)8s5L05A-z%Rcfr67Blzp@g7!d0@"
  django_superuser_username: "admin-status"
  django_superuser_password: "admin-status"
  django_superuser_email: "guy.tamari@nitzanim.tech"

redis:
  replicas: 1
  image:
    repository: redis
    tag: 4.0-alpine

storageClass:
  name: guy-tomer-storage-class
  type: gp2