apiVersion: v1
kind: Service
metadata:
  name: status-page
spec:
  selector:
    app: status-page
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
    - protocol: TCP
      port: 8001
      targetPort: 8001
